"""Initial baseline

Revision ID: fa309112c04a
Revises: 
Create Date: 2026-06-28 05:50:29.008543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa309112c04a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_control_integration')
    op.drop_table('hrms_sync')
    op.drop_table('hrms_sync_history')
    op.drop_table('project_mapping')
    op.drop_index(op.f('idx_alerts_employee'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_mustering'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_status'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('notification_routes')
    op.drop_index(op.f('idx_mustering_events_dept'), table_name='mustering_events')
    op.drop_index(op.f('idx_mustering_events_time'), table_name='mustering_events')
    op.drop_table('mustering_events')
    op.add_column('alert_actions', sa.Column('details', sa.String(), nullable=True))
    op.drop_constraint(op.f('alert_actions_alert_id_fkey'), 'alert_actions', type_='foreignkey')
    op.drop_column('alert_actions', 'comments')
    op.drop_column('alert_actions', 'alert_id')
    op.drop_column('attendance_events', 'similarity')
    op.alter_column('cameras', 'rtsp_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('employees_employee_code_unique'), 'employees', type_='unique')
    op.drop_column('facial_templates', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facial_templates', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('employees_employee_code_unique'), 'employees', ['employee_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('cameras', 'rtsp_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('attendance_events', sa.Column('similarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('alert_actions', sa.Column('alert_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alert_actions', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('alert_actions_alert_id_fkey'), 'alert_actions', 'alerts', ['alert_id'], ['id'])
    op.drop_column('alert_actions', 'details')
    op.create_table('mustering_events',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_employees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('present_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('missing_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('mustering_events_department_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('mustering_events_pkey'))
    )
    op.create_index(op.f('idx_mustering_events_time'), 'mustering_events', [sa.literal_column('event_time DESC')], unique=False)
    op.create_index(op.f('idx_mustering_events_dept'), 'mustering_events', ['department_id'], unique=False)
    op.create_table('notification_routes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_delivery_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('notification_routes_alert_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_routes_pkey'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raised_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raised_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('escalation_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('employee_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mustering_event_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('alerts_closed_by_fkey')),
    sa.ForeignKeyConstraint(['mustering_event_id'], ['mustering_events.id'], name=op.f('alerts_mustering_event_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('alerts_raised_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('idx_alerts_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('idx_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('idx_alerts_mustering'), 'alerts', ['mustering_event_id'], unique=False)
    op.create_index(op.f('idx_alerts_employee'), 'alerts', ['employee_id'], unique=False)
    op.create_table('project_mapping',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attendance_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mapped_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attendance_event_id'], ['attendance_events.id'], name=op.f('project_mapping_attendance_event_id_fkey')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('project_mapping_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_mapping_pkey'))
    )
    op.create_table('hrms_sync_history',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sync_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['hrms_sync.id'], name=op.f('hrms_sync_history_sync_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hrms_sync_history_pkey'))
    )
    op.create_table('hrms_sync',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sync_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('records_updated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hrms_sync_pkey'))
    )
    op.create_table('access_control_integration',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endpoint_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('credentials', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_sync_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('access_control_integration_pkey'))
    )
    # ### end Alembic commands ###
